<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tag', 'doctrine');

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $etiqueta
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $TagAnuncio
 * @property Doctrine_Collection $TagOrganizacion
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getEtiqueta()        Returns the current record's "etiqueta" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Doctrine_Collection getTagAnuncio()      Returns the current record's "TagAnuncio" collection
 * @method Doctrine_Collection getTagOrganizacion() Returns the current record's "TagOrganizacion" collection
 * @method Tag                 setId()              Sets the current record's "id" value
 * @method Tag                 setEtiqueta()        Sets the current record's "etiqueta" value
 * @method Tag                 setCreatedAt()       Sets the current record's "created_at" value
 * @method Tag                 setUpdatedAt()       Sets the current record's "updated_at" value
 * @method Tag                 setTagAnuncio()      Sets the current record's "TagAnuncio" collection
 * @method Tag                 setTagOrganizacion() Sets the current record's "TagOrganizacion" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('etiqueta', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TagAnuncio', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $this->hasMany('TagOrganizacion', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}