<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoAnuncio', 'doctrine');

/**
 * BaseTipoAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_tipo_anuncio
 * @property Doctrine_Collection $Anuncio
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombreTipoAnuncio()   Returns the current record's "nombre_tipo_anuncio" value
 * @method Doctrine_Collection getAnuncio()             Returns the current record's "Anuncio" collection
 * @method TipoAnuncio         setId()                  Sets the current record's "id" value
 * @method TipoAnuncio         setNombreTipoAnuncio()   Sets the current record's "nombre_tipo_anuncio" value
 * @method TipoAnuncio         setAnuncio()             Sets the current record's "Anuncio" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_anuncio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_tipo_anuncio', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Anuncio', array(
             'local' => 'id',
             'foreign' => 'tipo_anuncio_id'));
    }
}