<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ValoracionInstitucion', 'doctrine');

/**
 * BaseValoracionInstitucion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $puntos
 * @property string $observacion
 * @property integer $institucion_id
 * @property integer $usuario_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer               getId()             Returns the current record's "id" value
 * @method integer               getPuntos()         Returns the current record's "puntos" value
 * @method string                getObservacion()    Returns the current record's "observacion" value
 * @method integer               getInstitucionId()  Returns the current record's "institucion_id" value
 * @method integer               getUsuarioId()      Returns the current record's "usuario_id" value
 * @method timestamp             getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp             getUpdatedAt()      Returns the current record's "updated_at" value
 * @method ValoracionInstitucion setId()             Sets the current record's "id" value
 * @method ValoracionInstitucion setPuntos()         Sets the current record's "puntos" value
 * @method ValoracionInstitucion setObservacion()    Sets the current record's "observacion" value
 * @method ValoracionInstitucion setInstitucionId()  Sets the current record's "institucion_id" value
 * @method ValoracionInstitucion setUsuarioId()      Sets the current record's "usuario_id" value
 * @method ValoracionInstitucion setCreatedAt()      Sets the current record's "created_at" value
 * @method ValoracionInstitucion setUpdatedAt()      Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseValoracionInstitucion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('valoracion_institucion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('puntos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('observacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('institucion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}