<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoHorario', 'doctrine');

/**
 * BaseTipoHorario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_tipo_horario
 * @property integer $usuario_id
 * @property integer $anuncio
 * @property timestamp $created_at
 * @property Usuario $Usuario
 * @property Doctrine_Collection $HorarioAnuncio
 * @property Doctrine_Collection $HorarioUbicacion
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombreTipoHorario()   Returns the current record's "nombre_tipo_horario" value
 * @method integer             getUsuarioId()           Returns the current record's "usuario_id" value
 * @method integer             getAnuncio()             Returns the current record's "anuncio" value
 * @method timestamp           getCreatedAt()           Returns the current record's "created_at" value
 * @method Usuario             getUsuario()             Returns the current record's "Usuario" value
 * @method Doctrine_Collection getHorarioAnuncio()      Returns the current record's "HorarioAnuncio" collection
 * @method Doctrine_Collection getHorarioUbicacion()    Returns the current record's "HorarioUbicacion" collection
 * @method TipoHorario         setId()                  Sets the current record's "id" value
 * @method TipoHorario         setNombreTipoHorario()   Sets the current record's "nombre_tipo_horario" value
 * @method TipoHorario         setUsuarioId()           Sets the current record's "usuario_id" value
 * @method TipoHorario         setAnuncio()             Sets the current record's "anuncio" value
 * @method TipoHorario         setCreatedAt()           Sets the current record's "created_at" value
 * @method TipoHorario         setUsuario()             Sets the current record's "Usuario" value
 * @method TipoHorario         setHorarioAnuncio()      Sets the current record's "HorarioAnuncio" collection
 * @method TipoHorario         setHorarioUbicacion()    Sets the current record's "HorarioUbicacion" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoHorario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_horario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_tipo_horario', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('anuncio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasMany('HorarioAnuncio', array(
             'local' => 'id',
             'foreign' => 'tipo_horario_id'));

        $this->hasMany('HorarioUbicacion', array(
             'local' => 'id',
             'foreign' => 'tipo_horario_id'));
    }
}