<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Categoria', 'doctrine');

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_categoria
 * @property integer $categoria_padre_id
 * @property Doctrine_Collection $Organizacion
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getNombreCategoria()    Returns the current record's "nombre_categoria" value
 * @method integer             getCategoriaPadreId()   Returns the current record's "categoria_padre_id" value
 * @method Doctrine_Collection getOrganizacion()       Returns the current record's "Organizacion" collection
 * @method Categoria           setId()                 Sets the current record's "id" value
 * @method Categoria           setNombreCategoria()    Sets the current record's "nombre_categoria" value
 * @method Categoria           setCategoriaPadreId()   Sets the current record's "categoria_padre_id" value
 * @method Categoria           setOrganizacion()       Sets the current record's "Organizacion" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_categoria', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('categoria_padre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Organizacion', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));
    }
}