<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioCupon', 'doctrine');

/**
 * BaseUsuarioCupon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property integer $anuncio_cupon_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method integer      getUsuarioId()        Returns the current record's "usuario_id" value
 * @method integer      getAnuncioCuponId()   Returns the current record's "anuncio_cupon_id" value
 * @method timestamp    getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp    getUpdatedAt()        Returns the current record's "updated_at" value
 * @method UsuarioCupon setId()               Sets the current record's "id" value
 * @method UsuarioCupon setUsuarioId()        Sets the current record's "usuario_id" value
 * @method UsuarioCupon setAnuncioCuponId()   Sets the current record's "anuncio_cupon_id" value
 * @method UsuarioCupon setCreatedAt()        Sets the current record's "created_at" value
 * @method UsuarioCupon setUpdatedAt()        Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioCupon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_cupon');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('anuncio_cupon_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}