<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AnuncioEvento', 'doctrine');

/**
 * BaseAnuncioEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $coordenada_x
 * @property string $coordenada_y
 * @property string $telefono_evento
 * @property string $pagina_web_evento
 * @property integer $anuncio_id
 * @property integer $ciudad_id
 * @property Anuncio $Anuncio
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method string        getCoordenadaX()       Returns the current record's "coordenada_x" value
 * @method string        getCoordenadaY()       Returns the current record's "coordenada_y" value
 * @method string        getTelefonoEvento()    Returns the current record's "telefono_evento" value
 * @method string        getPaginaWebEvento()   Returns the current record's "pagina_web_evento" value
 * @method integer       getAnuncioId()         Returns the current record's "anuncio_id" value
 * @method integer       getCiudadId()          Returns the current record's "ciudad_id" value
 * @method Anuncio       getAnuncio()           Returns the current record's "Anuncio" value
 * @method AnuncioEvento setId()                Sets the current record's "id" value
 * @method AnuncioEvento setCoordenadaX()       Sets the current record's "coordenada_x" value
 * @method AnuncioEvento setCoordenadaY()       Sets the current record's "coordenada_y" value
 * @method AnuncioEvento setTelefonoEvento()    Sets the current record's "telefono_evento" value
 * @method AnuncioEvento setPaginaWebEvento()   Sets the current record's "pagina_web_evento" value
 * @method AnuncioEvento setAnuncioId()         Sets the current record's "anuncio_id" value
 * @method AnuncioEvento setCiudadId()          Sets the current record's "ciudad_id" value
 * @method AnuncioEvento setAnuncio()           Sets the current record's "Anuncio" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnuncioEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anuncio_evento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('coordenada_x', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('coordenada_y', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('telefono_evento', 'string', 11, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('pagina_web_evento', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('anuncio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ciudad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anuncio', array(
             'local' => 'anuncio_id',
             'foreign' => 'id'));
    }
}