<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HorarioUbicacion', 'doctrine');

/**
 * BaseHorarioUbicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $dia
 * @property time $hora_apertura_manana
 * @property time $hora_cierre_manana
 * @property time $hora_apertura_tarde
 * @property time $hora_cierre_tarde
 * @property integer $horario_corrido
 * @property integer $sucursal_id
 * @property Ubicacion $Ubicacion
 * 
 * @method integer          getId()                   Returns the current record's "id" value
 * @method string           getDia()                  Returns the current record's "dia" value
 * @method time             getHoraAperturaManana()   Returns the current record's "hora_apertura_manana" value
 * @method time             getHoraCierreManana()     Returns the current record's "hora_cierre_manana" value
 * @method time             getHoraAperturaTarde()    Returns the current record's "hora_apertura_tarde" value
 * @method time             getHoraCierreTarde()      Returns the current record's "hora_cierre_tarde" value
 * @method integer          getHorarioCorrido()       Returns the current record's "horario_corrido" value
 * @method integer          getSucursalId()           Returns the current record's "sucursal_id" value
 * @method Ubicacion        getUbicacion()            Returns the current record's "Ubicacion" value
 * @method HorarioUbicacion setId()                   Sets the current record's "id" value
 * @method HorarioUbicacion setDia()                  Sets the current record's "dia" value
 * @method HorarioUbicacion setHoraAperturaManana()   Sets the current record's "hora_apertura_manana" value
 * @method HorarioUbicacion setHoraCierreManana()     Sets the current record's "hora_cierre_manana" value
 * @method HorarioUbicacion setHoraAperturaTarde()    Sets the current record's "hora_apertura_tarde" value
 * @method HorarioUbicacion setHoraCierreTarde()      Sets the current record's "hora_cierre_tarde" value
 * @method HorarioUbicacion setHorarioCorrido()       Sets the current record's "horario_corrido" value
 * @method HorarioUbicacion setSucursalId()           Sets the current record's "sucursal_id" value
 * @method HorarioUbicacion setUbicacion()            Sets the current record's "Ubicacion" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHorarioUbicacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horario_ubicacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dia', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('hora_apertura_manana', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_cierre_manana', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_apertura_tarde', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_cierre_tarde', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('horario_corrido', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('sucursal_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ubicacion', array(
             'local' => 'sucursal_id',
             'foreign' => 'id'));
    }
}