<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DetalleHorarioAnuncio', 'doctrine');

/**
 * BaseDetalleHorarioAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $horario_anuncio_id
 * @property time $hora_inicio
 * @property time $hora_fin
 * @property HorarioAnuncio $HorarioAnuncio
 * 
 * @method integer               getId()                 Returns the current record's "id" value
 * @method integer               getHorarioAnuncioId()   Returns the current record's "horario_anuncio_id" value
 * @method time                  getHoraInicio()         Returns the current record's "hora_inicio" value
 * @method time                  getHoraFin()            Returns the current record's "hora_fin" value
 * @method HorarioAnuncio        getHorarioAnuncio()     Returns the current record's "HorarioAnuncio" value
 * @method DetalleHorarioAnuncio setId()                 Sets the current record's "id" value
 * @method DetalleHorarioAnuncio setHorarioAnuncioId()   Sets the current record's "horario_anuncio_id" value
 * @method DetalleHorarioAnuncio setHoraInicio()         Sets the current record's "hora_inicio" value
 * @method DetalleHorarioAnuncio setHoraFin()            Sets the current record's "hora_fin" value
 * @method DetalleHorarioAnuncio setHorarioAnuncio()     Sets the current record's "HorarioAnuncio" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleHorarioAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_horario_anuncio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('horario_anuncio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hora_inicio', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_fin', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HorarioAnuncio', array(
             'local' => 'horario_anuncio_id',
             'foreign' => 'id'));
    }
}