<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HorarioAnuncio', 'doctrine');

/**
 * BaseHorarioAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dia_id
 * @property time $hora_inicio
 * @property time $hora_fin
 * @property integer $tipo_horario_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Dia $Dia
 * @property TipoHorario $TipoHorario
 * @property Doctrine_Collection $Anuncio
 * @property Doctrine_Collection $ServicioEspecial
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getDiaId()            Returns the current record's "dia_id" value
 * @method time                getHoraInicio()       Returns the current record's "hora_inicio" value
 * @method time                getHoraFin()          Returns the current record's "hora_fin" value
 * @method integer             getTipoHorarioId()    Returns the current record's "tipo_horario_id" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method Dia                 getDia()              Returns the current record's "Dia" value
 * @method TipoHorario         getTipoHorario()      Returns the current record's "TipoHorario" value
 * @method Doctrine_Collection getAnuncio()          Returns the current record's "Anuncio" collection
 * @method Doctrine_Collection getServicioEspecial() Returns the current record's "ServicioEspecial" collection
 * @method HorarioAnuncio      setId()               Sets the current record's "id" value
 * @method HorarioAnuncio      setDiaId()            Sets the current record's "dia_id" value
 * @method HorarioAnuncio      setHoraInicio()       Sets the current record's "hora_inicio" value
 * @method HorarioAnuncio      setHoraFin()          Sets the current record's "hora_fin" value
 * @method HorarioAnuncio      setTipoHorarioId()    Sets the current record's "tipo_horario_id" value
 * @method HorarioAnuncio      setCreatedAt()        Sets the current record's "created_at" value
 * @method HorarioAnuncio      setUpdatedAt()        Sets the current record's "updated_at" value
 * @method HorarioAnuncio      setDia()              Sets the current record's "Dia" value
 * @method HorarioAnuncio      setTipoHorario()      Sets the current record's "TipoHorario" value
 * @method HorarioAnuncio      setAnuncio()          Sets the current record's "Anuncio" collection
 * @method HorarioAnuncio      setServicioEspecial() Sets the current record's "ServicioEspecial" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHorarioAnuncio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horario_anuncio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('dia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hora_inicio', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_fin', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipo_horario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dia', array(
             'local' => 'dia_id',
             'foreign' => 'id'));

        $this->hasOne('TipoHorario', array(
             'local' => 'tipo_horario_id',
             'foreign' => 'id'));

        $this->hasMany('Anuncio', array(
             'local' => 'id',
             'foreign' => 'horario_anuncio_id'));

        $this->hasMany('ServicioEspecial', array(
             'local' => 'id',
             'foreign' => 'horario_anuncio_id'));
    }
}