<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_usuario
 * @property string $contrasena
 * @property string $correo_electronico
 * @property string $nombre
 * @property string $apellido
 * @property string $avatar
 * @property integer $actividad
 * @property timestamp $ultimo_inicio_sesion
 * @property boolean $activo
 * @property string $perfil_facebook
 * @property string $perfil_twitter
 * @property string $perfil_googleplus
 * @property boolean $pref_correo_electronico_publico
 * @property integer $rol_id
 * @property integer $ciudad_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Ciudad $Ciudad
 * @property Rol $Rol
 * @property Doctrine_Collection $Categoria
 * @property Doctrine_Collection $ComentarioAnuncio
 * @property Doctrine_Collection $DenunciaAnuncio
 * @property Doctrine_Collection $DenunciaComentario
 * @property Doctrine_Collection $Organizacion
 * @property Doctrine_Collection $Seguidor
 * @property Doctrine_Collection $TipoEvento
 * @property Doctrine_Collection $TipoHorario
 * @property Doctrine_Collection $UsuarioCupon
 * @property Doctrine_Collection $ValoracionUbicacion
 * 
 * @method integer             getId()                              Returns the current record's "id" value
 * @method string              getNombreUsuario()                   Returns the current record's "nombre_usuario" value
 * @method string              getContrasena()                      Returns the current record's "contrasena" value
 * @method string              getCorreoElectronico()               Returns the current record's "correo_electronico" value
 * @method string              getNombre()                          Returns the current record's "nombre" value
 * @method string              getApellido()                        Returns the current record's "apellido" value
 * @method string              getAvatar()                          Returns the current record's "avatar" value
 * @method integer             getActividad()                       Returns the current record's "actividad" value
 * @method timestamp           getUltimoInicioSesion()              Returns the current record's "ultimo_inicio_sesion" value
 * @method boolean             getActivo()                          Returns the current record's "activo" value
 * @method string              getPerfilFacebook()                  Returns the current record's "perfil_facebook" value
 * @method string              getPerfilTwitter()                   Returns the current record's "perfil_twitter" value
 * @method string              getPerfilGoogleplus()                Returns the current record's "perfil_googleplus" value
 * @method boolean             getPrefCorreoElectronicoPublico()    Returns the current record's "pref_correo_electronico_publico" value
 * @method integer             getRolId()                           Returns the current record's "rol_id" value
 * @method integer             getCiudadId()                        Returns the current record's "ciudad_id" value
 * @method timestamp           getCreatedAt()                       Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()                       Returns the current record's "updated_at" value
 * @method Ciudad              getCiudad()                          Returns the current record's "Ciudad" value
 * @method Rol                 getRol()                             Returns the current record's "Rol" value
 * @method Doctrine_Collection getCategoria()                       Returns the current record's "Categoria" collection
 * @method Doctrine_Collection getComentarioAnuncio()               Returns the current record's "ComentarioAnuncio" collection
 * @method Doctrine_Collection getDenunciaAnuncio()                 Returns the current record's "DenunciaAnuncio" collection
 * @method Doctrine_Collection getDenunciaComentario()              Returns the current record's "DenunciaComentario" collection
 * @method Doctrine_Collection getOrganizacion()                    Returns the current record's "Organizacion" collection
 * @method Doctrine_Collection getSeguidor()                        Returns the current record's "Seguidor" collection
 * @method Doctrine_Collection getTipoEvento()                      Returns the current record's "TipoEvento" collection
 * @method Doctrine_Collection getTipoHorario()                     Returns the current record's "TipoHorario" collection
 * @method Doctrine_Collection getUsuarioCupon()                    Returns the current record's "UsuarioCupon" collection
 * @method Doctrine_Collection getValoracionUbicacion()             Returns the current record's "ValoracionUbicacion" collection
 * @method Usuario             setId()                              Sets the current record's "id" value
 * @method Usuario             setNombreUsuario()                   Sets the current record's "nombre_usuario" value
 * @method Usuario             setContrasena()                      Sets the current record's "contrasena" value
 * @method Usuario             setCorreoElectronico()               Sets the current record's "correo_electronico" value
 * @method Usuario             setNombre()                          Sets the current record's "nombre" value
 * @method Usuario             setApellido()                        Sets the current record's "apellido" value
 * @method Usuario             setAvatar()                          Sets the current record's "avatar" value
 * @method Usuario             setActividad()                       Sets the current record's "actividad" value
 * @method Usuario             setUltimoInicioSesion()              Sets the current record's "ultimo_inicio_sesion" value
 * @method Usuario             setActivo()                          Sets the current record's "activo" value
 * @method Usuario             setPerfilFacebook()                  Sets the current record's "perfil_facebook" value
 * @method Usuario             setPerfilTwitter()                   Sets the current record's "perfil_twitter" value
 * @method Usuario             setPerfilGoogleplus()                Sets the current record's "perfil_googleplus" value
 * @method Usuario             setPrefCorreoElectronicoPublico()    Sets the current record's "pref_correo_electronico_publico" value
 * @method Usuario             setRolId()                           Sets the current record's "rol_id" value
 * @method Usuario             setCiudadId()                        Sets the current record's "ciudad_id" value
 * @method Usuario             setCreatedAt()                       Sets the current record's "created_at" value
 * @method Usuario             setUpdatedAt()                       Sets the current record's "updated_at" value
 * @method Usuario             setCiudad()                          Sets the current record's "Ciudad" value
 * @method Usuario             setRol()                             Sets the current record's "Rol" value
 * @method Usuario             setCategoria()                       Sets the current record's "Categoria" collection
 * @method Usuario             setComentarioAnuncio()               Sets the current record's "ComentarioAnuncio" collection
 * @method Usuario             setDenunciaAnuncio()                 Sets the current record's "DenunciaAnuncio" collection
 * @method Usuario             setDenunciaComentario()              Sets the current record's "DenunciaComentario" collection
 * @method Usuario             setOrganizacion()                    Sets the current record's "Organizacion" collection
 * @method Usuario             setSeguidor()                        Sets the current record's "Seguidor" collection
 * @method Usuario             setTipoEvento()                      Sets the current record's "TipoEvento" collection
 * @method Usuario             setTipoHorario()                     Sets the current record's "TipoHorario" collection
 * @method Usuario             setUsuarioCupon()                    Sets the current record's "UsuarioCupon" collection
 * @method Usuario             setValoracionUbicacion()             Sets the current record's "ValoracionUbicacion" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_usuario', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('contrasena', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('correo_electronico', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('apellido', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('actividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ultimo_inicio_sesion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('activo', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('perfil_facebook', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('perfil_twitter', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('perfil_googleplus', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('pref_correo_electronico_publico', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('rol_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ciudad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ciudad', array(
             'local' => 'ciudad_id',
             'foreign' => 'id'));

        $this->hasOne('Rol', array(
             'local' => 'rol_id',
             'foreign' => 'id'));

        $this->hasMany('Categoria', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ComentarioAnuncio', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('DenunciaAnuncio', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('DenunciaComentario', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('Organizacion', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('Seguidor', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('TipoEvento', array(
             'local' => 'id',
             'foreign' => 'usuario_sugiere_id'));

        $this->hasMany('TipoHorario', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('UsuarioCupon', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('ValoracionUbicacion', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));
    }
}