<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HorarioUbicacion', 'doctrine');

/**
 * BaseHorarioUbicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dia_id
 * @property time $hora_apertura_manana
 * @property time $hora_cierre_manana
 * @property time $hora_apertura_tarde
 * @property time $hora_cierre_tarde
 * @property boolean $horario_corrido
 * @property integer $ubicacion_id
 * @property integer $tipo_horario_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Dia $Dia
 * @property TipoHorario $TipoHorario
 * @property Ubicacion $Ubicacion
 * 
 * @method integer          getId()                   Returns the current record's "id" value
 * @method integer          getDiaId()                Returns the current record's "dia_id" value
 * @method time             getHoraAperturaManana()   Returns the current record's "hora_apertura_manana" value
 * @method time             getHoraCierreManana()     Returns the current record's "hora_cierre_manana" value
 * @method time             getHoraAperturaTarde()    Returns the current record's "hora_apertura_tarde" value
 * @method time             getHoraCierreTarde()      Returns the current record's "hora_cierre_tarde" value
 * @method boolean          getHorarioCorrido()       Returns the current record's "horario_corrido" value
 * @method integer          getUbicacionId()          Returns the current record's "ubicacion_id" value
 * @method integer          getTipoHorarioId()        Returns the current record's "tipo_horario_id" value
 * @method timestamp        getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()            Returns the current record's "updated_at" value
 * @method Dia              getDia()                  Returns the current record's "Dia" value
 * @method TipoHorario      getTipoHorario()          Returns the current record's "TipoHorario" value
 * @method Ubicacion        getUbicacion()            Returns the current record's "Ubicacion" value
 * @method HorarioUbicacion setId()                   Sets the current record's "id" value
 * @method HorarioUbicacion setDiaId()                Sets the current record's "dia_id" value
 * @method HorarioUbicacion setHoraAperturaManana()   Sets the current record's "hora_apertura_manana" value
 * @method HorarioUbicacion setHoraCierreManana()     Sets the current record's "hora_cierre_manana" value
 * @method HorarioUbicacion setHoraAperturaTarde()    Sets the current record's "hora_apertura_tarde" value
 * @method HorarioUbicacion setHoraCierreTarde()      Sets the current record's "hora_cierre_tarde" value
 * @method HorarioUbicacion setHorarioCorrido()       Sets the current record's "horario_corrido" value
 * @method HorarioUbicacion setUbicacionId()          Sets the current record's "ubicacion_id" value
 * @method HorarioUbicacion setTipoHorarioId()        Sets the current record's "tipo_horario_id" value
 * @method HorarioUbicacion setCreatedAt()            Sets the current record's "created_at" value
 * @method HorarioUbicacion setUpdatedAt()            Sets the current record's "updated_at" value
 * @method HorarioUbicacion setDia()                  Sets the current record's "Dia" value
 * @method HorarioUbicacion setTipoHorario()          Sets the current record's "TipoHorario" value
 * @method HorarioUbicacion setUbicacion()            Sets the current record's "Ubicacion" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHorarioUbicacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('horario_ubicacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dia_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hora_apertura_manana', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_cierre_manana', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_apertura_tarde', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('hora_cierre_tarde', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('horario_corrido', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('ubicacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipo_horario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dia', array(
             'local' => 'dia_id',
             'foreign' => 'id'));

        $this->hasOne('TipoHorario', array(
             'local' => 'tipo_horario_id',
             'foreign' => 'id'));

        $this->hasOne('Ubicacion', array(
             'local' => 'ubicacion_id',
             'foreign' => 'id'));
    }
}