<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dia', 'doctrine');

/**
 * BaseDia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $dia
 * @property Doctrine_Collection $HorarioAnuncio
 * @property Doctrine_Collection $HorarioUbicacion
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getDia()              Returns the current record's "dia" value
 * @method Doctrine_Collection getHorarioAnuncio()   Returns the current record's "HorarioAnuncio" collection
 * @method Doctrine_Collection getHorarioUbicacion() Returns the current record's "HorarioUbicacion" collection
 * @method Dia                 setId()               Sets the current record's "id" value
 * @method Dia                 setDia()              Sets the current record's "dia" value
 * @method Dia                 setHorarioAnuncio()   Sets the current record's "HorarioAnuncio" collection
 * @method Dia                 setHorarioUbicacion() Sets the current record's "HorarioUbicacion" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('dia', 'string', 9, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 9,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HorarioAnuncio', array(
             'local' => 'id',
             'foreign' => 'dia_id'));

        $this->hasMany('HorarioUbicacion', array(
             'local' => 'id',
             'foreign' => 'dia_id'));
    }
}