<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ValoracionSucursal', 'doctrine');

/**
 * BaseValoracionSucursal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $puntos
 * @property string $observacion
 * @property integer $usuario_id
 * @property integer $sucursal_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Ubicacion $Ubicacion
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getPuntos()      Returns the current record's "puntos" value
 * @method string             getObservacion() Returns the current record's "observacion" value
 * @method integer            getUsuarioId()   Returns the current record's "usuario_id" value
 * @method integer            getSucursalId()  Returns the current record's "sucursal_id" value
 * @method timestamp          getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Ubicacion          getUbicacion()   Returns the current record's "Ubicacion" value
 * @method ValoracionSucursal setId()          Sets the current record's "id" value
 * @method ValoracionSucursal setPuntos()      Sets the current record's "puntos" value
 * @method ValoracionSucursal setObservacion() Sets the current record's "observacion" value
 * @method ValoracionSucursal setUsuarioId()   Sets the current record's "usuario_id" value
 * @method ValoracionSucursal setSucursalId()  Sets the current record's "sucursal_id" value
 * @method ValoracionSucursal setCreatedAt()   Sets the current record's "created_at" value
 * @method ValoracionSucursal setUpdatedAt()   Sets the current record's "updated_at" value
 * @method ValoracionSucursal setUbicacion()   Sets the current record's "Ubicacion" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseValoracionSucursal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('valoracion_sucursal');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('puntos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('observacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sucursal_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ubicacion', array(
             'local' => 'sucursal_id',
             'foreign' => 'id'));
    }
}