<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estado', 'doctrine');

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $nombre_estado
 * @property Doctrine_Collection $Ciudad
 * 
 * @method string              getId()            Returns the current record's "id" value
 * @method string              getNombreEstado()  Returns the current record's "nombre_estado" value
 * @method Doctrine_Collection getCiudad()        Returns the current record's "Ciudad" collection
 * @method Estado              setId()            Sets the current record's "id" value
 * @method Estado              setNombreEstado()  Sets the current record's "nombre_estado" value
 * @method Estado              setCiudad()        Sets the current record's "Ciudad" collection
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('id', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nombre_estado', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ciudad', array(
             'local' => 'id',
             'foreign' => 'estado_id'));
    }
}