<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ServicioEspecial', 'doctrine');

/**
 * BaseServicioEspecial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_servicio_especial
 * @property string $que_incluye
 * @property string $condiciones
 * @property string $descripcion
 * @property float $precio
 * @property string $imagen
 * @property integer $activo
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer          getId()                       Returns the current record's "id" value
 * @method string           getNombreServicioEspecial()   Returns the current record's "nombre_servicio_especial" value
 * @method string           getQueIncluye()               Returns the current record's "que_incluye" value
 * @method string           getCondiciones()              Returns the current record's "condiciones" value
 * @method string           getDescripcion()              Returns the current record's "descripcion" value
 * @method float            getPrecio()                   Returns the current record's "precio" value
 * @method string           getImagen()                   Returns the current record's "imagen" value
 * @method integer          getActivo()                   Returns the current record's "activo" value
 * @method timestamp        getCreatedAt()                Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()                Returns the current record's "updated_at" value
 * @method ServicioEspecial setId()                       Sets the current record's "id" value
 * @method ServicioEspecial setNombreServicioEspecial()   Sets the current record's "nombre_servicio_especial" value
 * @method ServicioEspecial setQueIncluye()               Sets the current record's "que_incluye" value
 * @method ServicioEspecial setCondiciones()              Sets the current record's "condiciones" value
 * @method ServicioEspecial setDescripcion()              Sets the current record's "descripcion" value
 * @method ServicioEspecial setPrecio()                   Sets the current record's "precio" value
 * @method ServicioEspecial setImagen()                   Sets the current record's "imagen" value
 * @method ServicioEspecial setActivo()                   Sets the current record's "activo" value
 * @method ServicioEspecial setCreatedAt()                Sets the current record's "created_at" value
 * @method ServicioEspecial setUpdatedAt()                Sets the current record's "updated_at" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServicioEspecial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('servicio_especial');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre_servicio_especial', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('que_incluye', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('condiciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('precio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}