<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TagOrganizacion', 'doctrine');

/**
 * BaseTagOrganizacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tag_id
 * @property integer $organizacion_id
 * @property Tag $Tag
 * @property Organizacion $Organizacion
 * 
 * @method integer         getId()              Returns the current record's "id" value
 * @method integer         getTagId()           Returns the current record's "tag_id" value
 * @method integer         getOrganizacionId()  Returns the current record's "organizacion_id" value
 * @method Tag             getTag()             Returns the current record's "Tag" value
 * @method Organizacion    getOrganizacion()    Returns the current record's "Organizacion" value
 * @method TagOrganizacion setId()              Sets the current record's "id" value
 * @method TagOrganizacion setTagId()           Sets the current record's "tag_id" value
 * @method TagOrganizacion setOrganizacionId()  Sets the current record's "organizacion_id" value
 * @method TagOrganizacion setTag()             Sets the current record's "Tag" value
 * @method TagOrganizacion setOrganizacion()    Sets the current record's "Organizacion" value
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTagOrganizacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag_organizacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tag_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('organizacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id'));

        $this->hasOne('Organizacion', array(
             'local' => 'organizacion_id',
             'foreign' => 'id'));
    }
}