<?php

/**
 * AnuncioEventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioEventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioEventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioEvento');
    }
}