<?php

/**
 * AnuncioCuponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnuncioCuponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnuncioCuponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnuncioCupon');
    }
}