<?php

/**
 * ComentarioAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComentarioAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComentarioAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ComentarioAnuncio');
    }
}