<?php

/**
 * DenunciaComentarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DenunciaComentarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DenunciaComentarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DenunciaComentario');
    }
}