<?php

/**
 * DenunciaAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DenunciaAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DenunciaAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DenunciaAnuncio');
    }
}