<?php

/**
 * DiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dia');
    }
}