<?php

/**
 * FotoAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotoAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotoAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotoAnuncio');
    }
}