<?php

/**
 * HorarioUbicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorarioUbicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorarioUbicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorarioUbicacion');
    }
}