<?php

/**
 * HorarioAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HorarioAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HorarioAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HorarioAnuncio');
    }
}