<?php

/**
 * Organizacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Organizacion extends BaseOrganizacion {
    public function save(Doctrine_Connection $conn = null) {
        $this->setUsuarioId(sfContext::getInstance()->getUser()->getAttribute('usuario_id', '','user_vars'));
        $this->setSalt(sha1($this->getId().'ñññ'.$this->getUsuarioId().date("d&M__Y;;||hisu")));
        $this->setToken(md5($this->getSalt().md5(rand(0, 99999))));
        return parent::save($conn);
    }
    
    public static function activarOrganizacion($organizacion_id){
        $query = Doctrine_Query::create()
                ->update('Organizacion')
                ->set('activa', true)
                ->where('id=?',$organizacion_id)
                ->execute();
        return true;
    }
}
