<?php

/**
 * OrganizacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrganizacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrganizacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Organizacion');
    }
}