<?php

/**
 * RolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rol');
    }
}