<?php

/**
 * SeguidorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguidorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeguidorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Seguidor');
    }
}