<?php

/**
 * ServicioEspecialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicioEspecialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicioEspecialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServicioEspecial');
    }
}