<?php

/**
 * TagOrganizacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagOrganizacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagOrganizacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagOrganizacion');
    }
}