<?php

/**
 * TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object TagTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Tag');
    }

    public function getTags($term){
        $query=  Doctrine_Query::create()
                ->select("*")
                ->from("Tag")
                ->where("etiqueta like '%".$term."%'");
        return $query->execute();
    }
    
    public function getIdTags($tags){
        $query=  Doctrine_Query::create()
                ->select('*')
                ->from("Tag")
                ->whereIn('etiqueta',$tags);
        return $query->execute();
    }
}