<?php

/**
 * TipoHorarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoHorarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoHorarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoHorario');
    }
}