<?php

/**
 * TipoEventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoEventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoEventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoEvento');
    }
}