<?php

/**
 * UbicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UbicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UbicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ubicacion');
    }
}