<?php

/**
 * UbicacionAnuncioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UbicacionAnuncioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UbicacionAnuncioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UbicacionAnuncio');
    }
}