<?php

/**
 * UbicacionAnuncio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UbicacionAnuncio extends BaseUbicacionAnuncio {
    public function save(Doctrine_Connection $conn = null) {
        $this->setAnuncioId(sfContext::getInstance()->getUser()->getAttribute('anuncio'));
        parent::save($conn);
    }
    public function guardar($ubicacion){
        $this->setUbicacionId($ubicacion);
        $this->save();
    }
}
