<?php

/**
 * Ubicacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    guammas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ubicacion extends BaseUbicacion {

    public function updateUbicacion(sfWebRequest $request) {
        $query = Doctrine_Query::create()
                ->update('Ubicacion')
                ->set('nombre',"'".$request->getParameter('ubicacion_nombre')."'")
                ->set('detalle_direccion',"'".$request->getParameter('ubicacion_direccion')."'")
                ->set('telefono_ppal',"'".$request->getParameter('ubicacion_telefono_ppal')."'")
                ->set('telefono_sec',"'".$request->getParameter('ubicacion_telefono_sec')."'")
                ->where('id=?',$request->getParameter('ubicacion_id'));
        return $query->execute();
    }
    
    public function save(Doctrine_Connection $conn = null) {
        $this->setPrincipal(self::isPrincipal());
        $this->setOrganizacionId(sfContext::getInstance()->getUser()->getAttribute("empresa"));
        $ret = parent::save($conn);
        if($this->getOrganizacion()->getActiva()){
            $this->updateLuceneIndex(sfContext::getInstance()->getUser()->getAttribute("empresa"));
        }
        return $ret;
    }
    
    public function nuevaUbicacion(sfWebRequest $request){
        $this->setRif($request->getParameter('rif'));
        $this->setNombre($request->getParameter('nombre'));
        $this->setTelefonoPpal($request->getParameter('telefono'));
        $this->setCoordenadaX($request->getParameter('coordenada_x'));
        $this->setCoordenadaY($request->getParameter('coordenada_y'));
        $this->setCiudadId($request->getParameter('ciudad_id'));
        $this->save();
    }

    private static function isPrincipal() {
        $principal = sfContext::getInstance()->getUser()->getAttribute("principal");
        if (is_bool($principal)) {
            return $principal;
        }
    }

    public function updateLuceneIndex($empresa) {
        
        $index = UbicacionTable::getLuceneIndex();

        if ($hit = $index->find('pk:' . $empresa)) {
            $index->delete($hit->id);
        }

        $doc = new Zend_Search_Lucene_Document();

        $stringIndex = new finda($empresa);
        $indexFinda = $stringIndex->indexConstructor();

        // store job primary key URL to identify it in the search results

        $doc->addField(Zend_Search_Lucene_Field::UnIndexed('pk', $empresa));

        $doc->addField(Zend_Search_Lucene_Field::UnStored('finda', $indexFinda, 'utf-8'));

        $index->addDocument($doc);
        $index->commit();
    }

}
