<?php

/**
 * UbicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UbicacionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UbicacionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Ubicacion');
    }

    public static function getLuceneIndex() {
        ProjectConfiguration::registerZend();

        if (file_exists($index = self::getLuceneIndexFile())) {
            return Zend_Search_Lucene::open($index);
        } else {
            return Zend_Search_Lucene::create($index);
        }
    }

    public static function getLuceneIndexFile() {
        return sfConfig::get('sf_data_dir') . '/lucene/sucursal.' . sfConfig::get('sf_environment') . '.index';
    }

    public function getForLuceneQuery($query) {
        $hits = self::getLuceneIndex()->find($query);

        $pks = array();
        foreach ($hits as $hit) {
            $pks[] = $hit->pk;
        }

        if (empty($pks)) {
            return array();
        }

        $query = Doctrine_Query::create()
                ->select('*')
                ->from("Organizacion")
                ->whereIn("id",$pks);

        return $query->execute();
    }

}