<?php

/**
 * UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Usuario');
    }

    public function getDatosUsuario($usuario,$clave) {
        $query = Doctrine_Query::create()
                ->select("*")
                ->from("Usuario usu")
                ->where("(nombre_usuario='" . $usuario . "' or correo_electronico='" . $usuario . "')")
                ->andWhere("contrasena=?", $clave)
                ->andWhere("activo=?", true)
                ->execute();
        return $query;
    }

}