<?php

/**
 * UsuarioCuponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioCuponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioCuponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioCupon');
    }
}