<?php

/**
 * ValoracionUbicacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValoracionUbicacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValoracionUbicacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValoracionUbicacion');
    }
}