<?php

/**
 * ValoracionSucursalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ValoracionSucursalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ValoracionSucursalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ValoracionSucursal');
    }
}