# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
activarUsuario:
  url: /activarUsuario/:usuarionombre
  param: { module: usuario, action: activar}
  options:
    column: usuarionombre

activarEmpresa:
  url: /activarEmpresa/:token
  param: { module: empresa, action: activar}
  options:
    column: token
    
getUbicaciones:
  url: /getSucursales
  param: { module: empresa, action: getSucursales}
    
crearCuentaREST:
  url: /usuario/crearCuentaREST
  param: {module: usuario, action: crearCuentaREST}

loginREST:
  url: /usuario/loginREST
  param: {module: usuario, action: loginREST}

busqueda:
  url:    /busqueda
  param:  { module: bienvenido, action: busqueda }

logout:
  url: /logout
  param: {module: usuario, action: logout }

editarUsuario:
  url: /perfil/:nombre_usuario
  param: { module: usuario, action: edit }

api:
  url: /api
  param: { module: bienvenido, action: api }
  requirements:
    sf_format: (?:xml|json|yaml)

exito:
  url:   /empresa/exito
  param: { module: empresa, action: exito }

comercio:
  url:   /empresa
  param: { module: empresa, action: new }
  
homepage:
  url:   /
  param: { module: bienvenido, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
